---
title: "Homework 1"
Author: Zichen Shu
output: github_document
---

This is my solution to HW1.

```{r}
library(tidyverse)
```


## Problem 1

Create a data frame with the specified elements.

```{r create df}
pro1_df = 
  tibble(
    samp = rnorm(10),
    samp_gt_0 = samp > 0,
    char_vec = c("a", "b", "c", "d","e", "f", "g", "h", "i", "j" ),
    factor_vec = factor(c("low","low","low","mod","mod","mod","mod","high","high","high"))
)

```

Take the mean of each variable in my data frame.

```{r take mean}
mean(pull(pro1_df, samp))
mean(pull(pro1_df, samp_gt_0))
mean(pull(pro1_df, char_vec))
mean(pull(pro1_df, factor_vec))
```
I can take the mean of number and logical but not character and factor

```{r try numeric}
as.numeric(pull(pro1_df, samp_gt_0)) * pull(pro1_df, samp)
as.factor(pull(pro1_df, samp_gt_0)) * pull(pro1_df, samp)
as.numeric(as.factor(pull(pro1_df, samp_gt_0))) * pull(pro1_df, samp)
```

## Problem 2

```{r}
data("penguins", package = "palmerpenguins")

plot_df = tibble(
  b_length = pull(penguins,bill_length_mm),
  f_length = pull(penguins,flipper_length_mm),
  species = pull(penguins,species)
)

ggplot(plot_df, aes(x = b_length, y = f_length, color = species)) + geom_point()

ggsave("plot.pdf", width = 3, height = 3)

```



